Restored counting files

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -151,42 +151,42 @@ jobs:
           echo "To override this, apply the 'ignore-sensitive-files-pr' label"          
           exit 1
 
-  # Count-Changed-Files:
-  #   if: ${{ github.actor != 'dependabot[bot]' }}
-  #   name: Checks if number of files changed is acceptable
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0  # Fetch all history for all branches and tags
+  Count-Changed-Files:
+    if: ${{ github.actor != 'dependabot[bot]' }}
+    name: Checks if number of files changed is acceptable
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Fetch all history for all branches and tags
 
-  #     - name: Get changed files
-  #       id: changed-files
-  #       run: |
-  #         # Get the base branch ref
-  #         BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
+      - name: Get changed files
+        id: changed-files
+        run: |
+          # Get the base branch ref
+          BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
 
-  #         # Count all changed files excluding .md files
-  #         ALL_CHANGED_FILES_COUNT=$(git diff --name-only --diff-filter=ACMRT $BASE_SHA ${{ github.event.pull_request.head.sha }} | grep -v -i "\.md$" | wc -l | tr -d ' ')
-  #         echo "all_changed_files_count=$ALL_CHANGED_FILES_COUNT" >> $GITHUB_OUTPUT
+          # Count all changed files excluding .md files
+          ALL_CHANGED_FILES_COUNT=$(git diff --name-only --diff-filter=ACMRT $BASE_SHA ${{ github.event.pull_request.head.sha }} | grep -v -i "\.md$" | wc -l | tr -d ' ')
+          echo "all_changed_files_count=$ALL_CHANGED_FILES_COUNT" >> $GITHUB_OUTPUT
 
-  #     - name: Echo number of changed files
-  #       env: 
-  #         CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
-  #       run: |
-  #         echo "Number of files changed: $CHANGED_FILES_COUNT"
+      - name: Echo number of changed files
+        env: 
+          CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
+        run: |
+          echo "Number of files changed: $CHANGED_FILES_COUNT"
 
-  #     - name: Check if the number of changed files is less than 100
-  #       if: steps.changed-files.outputs.all_changed_files_count > 100
-  #       env: 
-  #         CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
-  #       run: |
-  #         echo "Error: Too many files (greater than 100) changed in the pull request."
-  #         echo "Possible issues:"
-  #         echo "- Contributor may be merging into an incorrect branch."
-  #         echo "- Source branch may be incorrect please use develop as source branch."
-  #         exit 1
+      - name: Check if the number of changed files is less than 100
+        if: steps.changed-files.outputs.all_changed_files_count > 100
+        env: 
+          CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
+        run: |
+          echo "Error: Too many files (greater than 100) changed in the pull request."
+          echo "Possible issues:"
+          echo "- Contributor may be merging into an incorrect branch."
+          echo "- Source branch may be incorrect please use develop as source branch."
+          exit 1
 
   # Check-ESlint-Disable:
   #   name: Check for eslint-disable
