Test docusaurus and target branch

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -275,37 +275,37 @@ jobs:
       #     path: "./coverage/vitest/lcov.info"
       #     min_coverage: 86.6
 
-  # Test-Docusaurus-Deployment:
-  #   name: Test Deployment to https://docs-plugin.talawa.io
-  #   runs-on: ubuntu-latest
-  #   needs: [Test Application]
-  #   # Run only if the develop branch and not dependabot
-  #   if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.base.ref == 'develop' }}
-  #   steps:
-  #     - name: Checkout the Repository
-  #       uses: actions/checkout@v4
-  #     - name: Set up Node.js
-  #       uses: actions/setup-node@v4
-  #       with:
-  #         node-version: '24.x' 
-  #     - name: Install dependencies
-  #       working-directory: ./docs
-  #       run: npm install
-  #     - name: Test building the website
-  #       working-directory: ./docs
-  #       run: npm run build
+  Test-Docusaurus-Deployment:
+    name: Test Deployment to https://docs-plugin.talawa.io
+    runs-on: ubuntu-latest
+    needs: [Test Application]
+    # Run only if the develop branch and not dependabot
+    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.base.ref == 'develop' }}
+    steps:
+      - name: Checkout the Repository
+        uses: actions/checkout@v4
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '24.x' 
+      - name: Install dependencies
+        working-directory: ./docs
+        run: npm install
+      - name: Test building the website
+        working-directory: ./docs
+        run: npm run build
 
-  # Check-Target-Branch:
-  #   if: ${{ github.actor != 'dependabot[bot]' }}
-  #   name: Check Target Branch
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check if the target branch is develop
-  #       if: github.event.pull_request.base.ref != 'develop'
-  #       run: |
-  #         echo "Error: Pull request target branch must be 'develop'. Please refer PR_GUIDELINES.md"
-  #         echo "Error: Close this PR and try again."
-  #         exit 1
+  Check-Target-Branch:
+    if: ${{ github.actor != 'dependabot[bot]' }}
+    name: Check Target Branch
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if the target branch is develop
+        if: github.event.pull_request.base.ref != 'develop'
+        run: |
+          echo "Error: Pull request target branch must be 'develop'. Please refer PR_GUIDELINES.md"
+          echo "Error: Close this PR and try again."
+          exit 1
 
   # Python-Compliance:
   #   name: Check Python Code Style
